### ISSUE TITLE
Installing with npm @latest Not Working

### ISSUE THREAD

**Issue by stevepop** [s4l1h/vue-toastr#10]
Following your install instructions to install for Vue2
`npm install vue-toastr@^latest --save` gives the following errors;
```
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "vue-toastr@^latest" "--save"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! No compatible version found: vue-toastr@^latest
npm ERR! Valid install targets:
npm ERR! 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/steve/devapps/sites/vue2-naijaprizes/npm-debug.log
```
I had to specify by version before I could install. Can you fix this for people who might know what to do in case this happens?
Thanks!

**Comment by s4l1h** [comment]
**latest** is a special name in this npm.

https://docs.npmjs.com/cli/install

npm install vue-toastr@latest --save // install last published version. Tag Name **latest**

npm install vue-toastr@^2.0.1 --save // install latest version 2.x

npm install vue-toastr@2.0.1 --save // install specific version 2.0.1


npm install vue-toastr@^latest --save // wrong **^latest** is invalid package tag and version name.
