### ISSUE TITLE
this.$root refers to the root instance, not app instance

### ISSUE THREAD

**Issue by limuxy** [s4l1h/vue-toastr#14]
In vue.js 2:

I inserted  `<vue-toastr ref="toastr"></vue-toastr>` into `App` template, so according to the doc, I should be able to use `this.$root.$refs.toastr.e("ERRROR MESSAGE")`  in any child component

However `this.$root` actually refers to the root instance which is initialized by `new Vue()` , it's not the actual `App` instance where I include toastr

Now I can only access app instance by `this.$root.$children[0]` thus toastr by  `this.$root.$children[0].$refs.toastr.e("ERRROR MESSAGE")` , which looks ugly....

Any suggestion?

**Comment by s4l1h** [comment]
Can you share code? Vue version etc..

Eg: http://codepen.io/s4l1h/pen/jBbmWY

**Comment by limuxy** [comment]
@s4l1h 

By using vue.js's official webpack boilerplate, the `App` template is in a separate .vue file, which causes `$root`  refers to the root instance instead of the app instance. That's the problem.

Pls see this: http://codepen.io/limuxy/pen/zZvyLW

**Comment by limuxy** [comment]
@s4l1h of course I can use `this.$refs.toastr` in app, but it's not possible to access toastr in app's child components .... 
I understand this is not an issue of toastr, but just a problem of how to use it. I'll close it for now

**Comment by s4l1h** [comment]
@limuxy Best way, add toast to root component.
> `<div> <App/> <vue-toastr ref="toastr"></vue-toastr> </div>`
http://codepen.io/s4l1h/pen/jBbmWY

**div** is important! without div you can get error message 

> Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.)

**Comment by limuxy** [comment]
@s4l1h ah... yes this works. Thanks for the solution!
