### ISSUE TITLE
 Error using component

### ISSUE THREAD

**Issue by ARCHAMO** [s4l1h/vue-toastr#16]
Goodnight. I have followed the steps but what I get is this error.

Uncaught (in promise) TypeError: Can not read property 's' of undefined
    At eval (eval at <anonymous> (app.js: 1290), <anonymous>: 64:45)

I am using vue 2.2.6. And I do the import and registration of the component in my main.js.

**Comment by s4l1h** [comment]
Can you share code?

**Comment by ARCHAMO** [comment]
Good morning. I send you the step by step of the execution and implementation in my project. Thank you

[Case Toastr.docx](https://github.com/s4l1h/vue-toastr/files/916512/Case.Toastr.docx)

**Comment by s4l1h** [comment]
Hi,
Not possible this style help.
I think the problem is caused by component usage.
Can you read this issue? https://github.com/s4l1h/vue-toastr/issues/14
