### ISSUE TITLE
Component throws Vue tip

### ISSUE THREAD

**Issue by ipa1981** [s4l1h/vue-toastr#17]
When using component, even demo on http://s4l1h.github.io/vue-toastr/ a warning is thrown in console:

```
[Vue tip]: <toast v-for="mm in m">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

found in

---> <VueToastr>
       <Root>
```

**Comment by NicolaiRamsby** [comment]
Experiencing this issue too. Would be great if a 🔑 is added to the <toast> v-for.

**Comment by s4l1h** [comment]
@NicolaiRamsby  and @ipa1981  thanks.
