### ISSUE TITLE
HELP vuejs 2

### ISSUE THREAD

**Issue by jffsn** [s4l1h/vue-toastr#18]
Guys

I'm using vuejs 2

I added the component

Import Toastr from 'vue-toastr'

And

Components: {
     'Vue-toastr': Toastr
   },

And I'm calling you like this

Created () {
     This. $ Root. $ Refs.toastr.e ('ERRROR MESSAGE')
   },

ERROR
TypeError: Cannot read property 'e' of undefined

Thanks

**Comment by jffsn** [comment]
And

A doubt

As I add the package globally in my project

For example in main.js / app.vue so that I use in all components

Thanks

**Comment by s4l1h** [comment]
Can you read this issue? https://github.com/s4l1h/vue-toastr/issues/14

**Comment by jffsn** [comment]
Lol

Thank you very much
