### ISSUE TITLE
HELP: override template

### ISSUE THREAD

**Issue by jffsn** [s4l1h/vue-toastr#19]
Hi guys,

How do I overwrite the template?

For example:

Border-radius
Width toast-bottom-full-width that is not 100%

In addition to the css I would like to change html also for example when the position is toast-bottom-full-width or toast-top-full-width the message stay in the bootstrap container position

What is the best practice and structure for this?

Thank you

**Comment by s4l1h** [comment]
http://codepen.io/s4l1h/pen/aWPxRG

you can from access css.

or if you use webpack fork and change less file.

`require('vue-toastr/src/vue-toastr.less');`
to

`require('myToast.less');`

https://github.com/s4l1h/vue-toastr#with-npm--babel
