### ISSUE TITLE
progressBar & newestOnTop Options

### ISSUE THREAD

**Issue by Jielde** [s4l1h/vue-toastr#21]
Hi,

I'd like to know if you're going to add options :
    progressBar
    newestOnTop

Thx :)

--------

Démo : http://codeseven.github.io/toastr/demo.html

**Comment by s4l1h** [comment]
Good feature but i dont have time now.can wait for me or you can contribute **pull request**

Thanks

**Comment by s4l1h** [comment]
@Jielde https://github.com/s4l1h/vue-toastr/commit/6dc235b9a5b66e888dc443082f5323c2b53fd47b
Progress Bar added.

**Comment by Jielde** [comment]
Whaou, sorry I did not have time to look before, thank you very much for your work :)
----
Whaou, désolé je n'ai pas eu le temps de regarder avant, merci beaucoup pour ton travail :)

**Comment by u01jmg3** [comment]
Any chance of getting the `newestOnTop` option added?
