### ISSUE TITLE
preventDuplicates and clearAll Options

### ISSUE THREAD

**Issue by tiagocardosos** [s4l1h/vue-toastr#22]
Hi,

I'd like to know if you're going to add options :
preventDuplicates
clearAll

I'm having problems with the new version. Look at my screen

<img width="388" alt="screen shot 2017-07-05 at 21 22 45" src="https://user-images.githubusercontent.com/1429801/27891686-8e3f573c-61d1-11e7-9ae5-e399b69a7ad6.png">

**Comment by voogryk** [comment]
I add this options in pull-request https://github.com/s4l1h/vue-toastr/pull/24

**Comment by voogryk** [comment]
if you want you can use https://github.com/voogryk/cbp-vue-toastr - thats my clone of this repositories with npm package and those changes. but I hope @s4l1h would confirm my pull request as fast as he can.

**Comment by tiagocardosos** [comment]
@voogryk tanks for solution 👍

**Comment by s4l1h** [comment]
@voogryk thanks

**Comment by voogryk** [comment]
@s4l1h if u want we can work together on this plugin. I need it for my work but, it hasn't got a lot of features.
