### ISSUE TITLE
Less Loader Error

### ISSUE THREAD

**Issue by tomshaw** [s4l1h/vue-toastr#31]
Following the instructions produces the following error. 

```
ERROR in ./node_modules/vue-toastr/src/vue-toastr.less
  Module parse failed: Unexpected token (2:0)
  You may need an appropriate loader to handle this file type.
  | // Mix-ins
  | .borderRadius(@radius) {
  |     -moz-border-radius: @radius;
  |     -webkit-border-radius: @radius;
   @ ./src/renderer/main.js 17:0-41
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js
```

**Comment by s4l1h** [comment]
@tomshaw This problem is about electron project.
https://simulatedgreg.gitbooks.io/electron-vue/content/en/using_pre-processors.html
Could you change vue-toastr.less to  vue-toastr.scss but you need install first 
"npm install --save-dev sass-loader node-sass"

**Comment by tomshaw** [comment]
Nailed it. I'm using the Electron Vuetify boilerplate. https://github.com/vuetifyjs/electron

Thank you!
