### ISSUE TITLE
Is it possible to use this package without compiler?

### ISSUE THREAD

**Issue by gustawdaniel** [s4l1h/vue-toastr#33]
I installed this package and added to `main.js` these lines

```
import Toastr from 'vue-toastr';
// require('vue-toastr/src/vue-toastr.scss');

// Vue.use(Toastr);
Vue.use(Toastr);
```

I saw error:

```
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
```

Is it possible to use this package without compiler?

**Comment by s4l1h** [comment]
@gustawdaniel  Could you check out latest version( 2.0.14 )

**Comment by ejwaibel** [comment]
Still getting this message with latest 2.0.14 version.

**Comment by s4l1h** [comment]
@ejwaibel @gustawdaniel could you share code?

**Comment by ferm10n** [comment]
Hey, not sure why this issue was closed. Anyway I thought it was simple enough to convert the templates into render functions, so I created this PR which eliminates the need for the compiler https://github.com/s4l1h/vue-toastr/pull/41
