### ISSUE TITLE
toastr.removeByType shouldn't be the only viable option for removing a toastr

### ISSUE THREAD

**Issue by cloudybrain** [s4l1h/vue-toastr#37]
Because this library doesn't have any async functions, it would be nice to mimic the integration of this plugin into sites that utilize ajax/promises.

The way that I hook this plugin is, is because the ajax request is sent out, I display an information pop up on the screen, and upon success or failure, I remove the info and replace it with the respective new message. Like this:

     var vm = this;

        $.ajax({
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          url: '/api/ExampleAPI',
          data: function() {
               vm.$toastr.i("Waiting for response!");,
          }
          success: function (json) {
               vm.$toastr.removeByType("info");
               vm.$toastr.s("Success!");
          },
           error: function(json){
               vm.$toastr.removeByType("info");
               vm.$toastr.e("Error!");
            }
        });

The problem comes when there are several ajax requests made, where this particular function would remove all info messages on the screen.

So I'm requesting that there should be a new attribute called id, where you associate a number or name,

    this.$root.$refs.toastr.Add({
        id: "EasyToastr"
        title: "Easy Toast", // Toast Title
        msg: "Hi", // Message
    });

then you can remove this by:

   this.$root.$refs.toastr.Remove("EasyToastr");

That way I can pin point which messages to remove.

**Comment by cloudybrain** [comment]
I did see you can do something like this:

    var VooAaa = this.$refs.toastr.Add({
        title: 'Hello',
        msg: 'Im a message'
   });

   this.$refs.toastr.Close(VooAaa);


But you'd now be running into keeping a global store of running toastrs, as these toastrs could be called from several files. If there was an index, or name I could use to it, this would help remove the need for wiring a global store.

**Comment by s4l1h** [comment]
https://github.com/s4l1h/vue-toastr/blob/master/src/vue-toastr.js#L38

We have data.index variable it's increasing by automatic.

Maybe we can change api if index is not empty give the index(id).

like that


```
var VooAaa = this.$refs.toastr.Add({
    index:'woaid',
    title: 'Hello',
    msg: 'Im a message'
 });
```

` this.$refs.toastr.Close({ index:'woaid'});
`
or

` this.$refs.toastr.CloseById('woaid');`

**Comment by s4l1h** [comment]
@cloudybrain done it.
