### ISSUE TITLE
Hold on hover?

### ISSUE THREAD

**Issue by EPinci** [s4l1h/vue-toastr#42]
Hello,

is there a way to have the progress bar of a toast "halt" if the toast is hovered and resume when left?
This way users can slow relevant toasts for the time needed to read.

Thank you!

**Comment by s4l1h** [comment]
@EPinci It doesn't have like that options at the moment.
We should refractory the progress bar section as result.It will be able to do that.

**Comment by s4l1h** [comment]
I have just published new version of plugin. which is include this issue fix.
2.1.0
