### ISSUE TITLE
How would you exclude styling injection?

### ISSUE THREAD

**Issue by u01jmg3** [s4l1h/vue-toastr#43]
- Is it possible to exclude injecting [the styling](https://github.com/s4l1h/vue-toastr/blob/master/src/components/Toast.vue#L141-L143) so customised colours can be applied in a custom version of [`vue-toastr.scss`](https://github.com/s4l1h/vue-toastr/blob/master/src/vue-toastr.scss)?

  - [vue-toastr.common.js#L431-L436](https://github.com/s4l1h/vue-toastr/blob/master/dist/vue-toastr.common.js#L431-L436)
  - [vue-toastr.esm.js#L429-L434](https://github.com/s4l1h/vue-toastr/blob/master/dist/vue-toastr.esm.js#L429-L434)
  - [vue-toastr.umd.js#L435-L440](https://github.com/s4l1h/vue-toastr/blob/master/dist/vue-toastr.umd.js#L435-L440)

**Comment by s4l1h** [comment]
I have removed **scoped** keyword from Toast.vue file  you can overwrite your css file.

https://github.com/s4l1h/vue-toastr/commit/6898410e5f73823b014c59cbc84f7b7406bb1fca

**Comment by u01jmg3** [comment]
Thanks for the quick reply.

Can you explain how I would make use of a custom version of `vue-toastr.scss`?

**Comment by s4l1h** [comment]
@u01jmg3 you can use **[style property](https://s4l1h.github.io/vue-toastr/toast_options.html)**
or you can create custom css file and overwrite vue-toastr.scss ,you might use **css important! property**.

if you are using webpack you can access without style and non plugin toastr component.
`import Toastr from "vue-toastr/src/components/Toastr.vue";
` 


For more details 
https://github.com/s4l1h/vue-toastr/blob/master/src/components/VueToastr.vue
https://github.com/s4l1h/vue-toastr/blob/master/src/index.js

**Comment by s4l1h** [comment]
after 2.1.2 you can use **defaultClassNames** and **classNames** options for overwrite classes.
I made demo for you.
https://codepen.io/s4l1h/pen/PyaRGQ
