### ISSUE TITLE
Passing argument into OnClicked method

### ISSUE THREAD

**Issue by mrdigitalau** [s4l1h/vue-toastr#45]
Hi, thanks for this great plugin

I have been trying to pass an argument to the onClicked method and it always comes back as undefined.

Is this possible?

```
this.$toastr.s(
				{

						msg:"New SMS arrived from " + e.name + ": " + e.message + "",
						clickClose: true,
						timeout:0,
						type:'success',
						onClicked: (e)=>{

				                        console.log(e)
						}
					
				},
					
					
			);

```

**Comment by s4l1h** [comment]
You should use **Add** function for create toast from object.
http://s4l1h.github.io/vue-toastr/started.html#create-toast

Maybe you could create Vue.js method like this.
```js
function createToastMessage(e) {
    this.$toastr.Add({
        msg: "New SMS arrived from " + e.name + ": " + e.message + "",
        clickClose: true,
        timeout: 0,
        type: 'success',
        onClicked: (e) => {
          	//window.location.href=e.link;
            console.log(e)
        }
    });
}
```

**Comment by mrdigitalau** [comment]
Thank you for this.
It still does not seem to pass the object into the onClicked function.
I can console.log the object inside the function, but when passed into the OnClick function, it comes back as null.
Have you been successfully able to pass an argument into the onClicked function?

Cheers

**Comment by mrdigitalau** [comment]
Sorry, it comes back as "undefined" as opposed to "null"

**Comment by s4l1h** [comment]
My bad. Could you try this.
also I made demo for you : https://codesandbox.io/s/vue-template-or5zw
```js
function createToastMessage(e) {
    this.$toastr.Add({
        msg: "New SMS arrived from " + e.name + ": " + e.message + "",
        clickClose: true,
        timeout: 0,
        type: 'success',
        onClicked: () => {
          	//window.location.href=e.link;
            console.log(e)
        }
    });
}
```


Note: This problem not related to the library. It's about javascript you need to achieve.

**Comment by mrdigitalau** [comment]
Mr Kadir thank you for taking the time to explain this. I did another test based on your explanation and realised I did not need to pass the argement into the onClicked function for it to be able to be used within it.

It works now thank you again for your time and amazing plugin. Much appreciated.
