### ISSUE TITLE
Apply animation on toastr

### ISSUE THREAD

**Issue by lunwhl** [s4l1h/vue-toastr#46]
Hi, I have added the css below and add it into className but i still dont see the fade in animation for the toast.

`@-webkit-keyframes fadeIn {
    from {
      opacity: 0;
    }
  
    to {
      opacity: 1;
    }
  }
  
  @keyframes fadeIn {
    from {
      opacity: 0;
    }
  
    to {
      opacity: 1;
    }
  }
  
  .fadeIn {
    -webkit-animation-name: fadeIn;
    animation-name: fadeIn;
  }`

Please help.

**Comment by s4l1h** [comment]
Can you provide the code?

http://s4l1h.github.io/vue-toastr/toast_options.html

You can achieve that via classNames or style options.

Did you check the demo code out? https://github.com/s4l1h/vue-toastr/blob/master/demo/Demo.vue

**Comment by lunwhl** [comment]
In your demo, you have written this.

`this.$toastr.defaultClassNames = ["animated", "zoomInUp"];`

May I know how you declare the animated class?
Cause I have no idea what to do now.

**Comment by s4l1h** [comment]
That the demo code achieve to inject **css class** to  all of the toast.
That means if any toast created  the code inject to 

> **class="animated zoomInUp"**

Can you have a look this link : https://codepen.io/s4l1h/pen/PyaRGQ

If you provide your project code about vue-toastr I could help you.

**Comment by lunwhl** [comment]
Hi @s4l1h,
this is my codepen. 
https://codepen.io/lunwhl/pen/zYYQGvE

I wanted to add animation when toast is out.

**Comment by s4l1h** [comment]
@lunwhl the problem is not related with the library. Here is the demo with **animate.css**
https://codepen.io/s4l1h/pen/VwwOoxM

https://github.com/daneden/animate.css

**Comment by lunwhl** [comment]
@s4l1h thx. u solved my problem
