### ISSUE TITLE
animated for out dont work

### ISSUE THREAD

**Issue by Omarillo** [s4l1h/vue-toastr#50]

**Comment by s4l1h** [comment]
@Omarillo animate.css is not part of vue-toastr project. 
https://daneden.github.io/animate.css/
If you want to use that you have to include animate.css file to your project as you can see on [the demo](https://codepen.io/s4l1h/pen/PyaRGQ)

**Comment by Omarillo** [comment]
in the demo there is no exit animation, if I put classNames: ["animated", "fadeOut"] it is hidden at the moment, how can I configure the animation to enter and exit, thank you very much for your time and the quick response ..

**Comment by s4l1h** [comment]
I see.
You can do that with setTimeout  function but It's quite painfull.

Demo: https://codepen.io/s4l1h/pen/VwwOoxM


```js
   this.$toastr.Add({
      title: "Test animate", // Toast Title
      msg: "testing fade", // Message
      timeout: 4000, // Remember defaultTimeout is 5 sec..
      position: "toast-top-center", // Toast Position.
      type: "error", // Toast type,
      classNames: ["animated slideInLeft"],
      onCreated() {
        setTimeout(() => {
          this.classNames.push("slideOutRight");
        }, 3000);
      }
    });
```

**Comment by Omarillo** [comment]
Ok, thank you so much!!!!!! works super, take care!!!!
