### ISSUE TITLE
Remove default css

### ISSUE THREAD

**Issue by X5I** [s4l1h/vue-toastr#52]
Hey, 

Is it possible to remove the default css block added to our pages and add directly scss file ?

**Comment by s4l1h** [comment]
Unfortunately it is not possible. SCSS file comes with Toastr.vue component.

https://github.com/s4l1h/vue-toastr/blob/master/src/components/Toastr.vue#L252

**Comment by u01jmg3** [comment]
Non-issue that can be closed?
