### ISSUE TITLE
change less to sass

### ISSUE THREAD

**Issue by carloscuatin** [s4l1h/vue-toastr#8]

**Comment by s4l1h** [comment]
Direct ported from : https://github.com/CodeSeven/toastr/blob/master/toastr.less

What is wrong with less?

**Comment by cgarnier** [comment]
Could you provide a builded css to avoid to have to install less stuff ?

**Comment by s4l1h** [comment]
if your ask for compiler
less compiler need only **development**.

if your builded css
https://unpkg.com/vue-toastr@latest/dist/ 
**vue-toastr.min.css**
file size: 5.8 kb 
gzip size: 2.8 KB

if you write problem i can help you.
