### ISSUE TITLE
not:this.$root.$refs.toastr.e(message);

### ISSUE THREAD

**Issue by ShieldCN** [s4l1h/vue-toastr#9]
it's : this.$refs.toastr.e(message);
not:this.$root.$refs.toastr.e(message);
it's wrong in readme,and i try it one hour!

**Comment by s4l1h** [comment]
If you have installed the main component.

we can access this.$root https://vuejs.org/v2/api/#vm-root

https://github.com/s4l1h/vue-toastr/blob/master/index.html#L27

https://github.com/s4l1h/vue-toastr/blob/master/demo.js#L12
